# This small crate exists only so `mdbook test` can link the external crates
# used by the book's examples. List dependencies here and run `cargo build`;
# the compiled .rlib files will be placed in target/debug/deps for
# `mdbook test -L` to use.
#
# Add any other packages needed by the examples to [dependencies] below.
[package]
name = "book-test-deps"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
rand = "0.10"
thiserror = "2.0.18"
anyhow = "1.0.102"

# Packages used by Chapter 12 (async)
futures = "0.3"
mio = { version = "1", features = ["os-poll", "net"] }
tokio = { version = "1", features = ["full", "test-util"] }
tokio-util = { version = "0.7", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync", "net", "time", "io-util"] }
